with open('src/context/AppStateContext.tsx', 'r', encoding='utf-8') as f:
    lines = f.readlines()

# find index of `const PRODUCTS_SEED_KEY =`
start_idx = -1
end_idx = -1

for i, line in enumerate(lines):
    if "const PRODUCTS_SEED_KEY =" in line:
        start_idx = i
    if start_idx != -1 and line.strip() == "];" and i < 500:
        end_idx = i + 1
        break

print(f"Replacing lines {start_idx+1} to {end_idx}")

products_seed_code = '''const PRODUCTS_SEED_KEY = 'mtn_hub_products_official_v5';
const SEED_DATA_KEYS = [
  'customers',
  'leads',
  'opportunities',
  'documents',
  'approvals',
  'tasks',
  'users',
  'notifications',
];

// ================================================================
// MTN GHANA ENTERPRISE PRODUCT CATALOGUE SEED DATA
// Grounded strictly in "Enterprise Products (3).xlsx" / Sheet: products
// Product Owners: Afua, Eunice, Justin
// Categories: Mobile | Converged | Digital | Fixed
// ================================================================
const MTN_GHANA_PRODUCTS_SEED: EnterpriseProduct[] = [
  // ── 1. AFA Bundle (Mobile) ──
  {
    id: 'PROD-MOB-AFA',
    name: 'AFA Bundle',
    serviceType: 'Mobile',
    category: 'Mobile',
    description: 'A special mobile subscription for data, voice and sms services tailored for farmers.',
    fullDescription: 'A special mobile subscription for data, voice and sms services tailored for farmers. Designed to enhance agricultural productivity with affordable and reliable communication.',
    pricingModel: 'Fixed Pricing (Different packages)',
    productOwner: 'Afua',
    targetSegments: ['SME', 'Large Enterprise'],
    technicalRequirements: ['MTN SIM Cards', 'Farmer Association Registration'],
    status: 'Active',
    iconName: 'Sprout',
    keyFeatures: ['Discounted agricultural voice rates', 'Subsidized data bundles', 'Weather & market price SMS alerts'],
    slaOptions: ['Standard Mobile SLA (99.0%)'],
  },
  // ── 2. APN Solutions (Converged) ──
  {
    id: 'PROD-CONV-APN',
    name: 'APN Solutions',
    serviceType: 'Converged',
    category: 'Converged',
    description: "MTN Access Point Name Solutions enables devices such as PCs or POS devices to connect to company internal networks and databases securely.",
    fullDescription: "MTN Access Point Name Solutions or services enables devices such as Personal Computers or Mobile Devices such as point of sale (POS) devices in various geographical areas to connect to their databases and servers or a company's internal network.",
    pricingModel: 'Number of SIMs, Data Package, APN Connectivity Type (Internet, Leased Line), Medium (Direct Fiber, GPON Fiber, MW, Mobile), Customer segment (LE, SME)',
    productOwner: 'Afua',
    targetSegments: ['Large Enterprise', 'SME', 'Multinational'],
    technicalRequirements: ['Dedicated Private APN', 'IPSec Tunnel / Leased Line', 'Radius / AAA Authentication'],
    status: 'Active',
    iconName: 'Waypoints',
    keyFeatures: ['Isolated corporate APN gateway', 'Encrypted end-to-end data tunnel', 'Static IP per device support', 'Multi-medium connectivity'],
    slaOptions: ['Platinum (99.95%)', 'Gold (99.5%)'],
  },
  // ── 3. Association Bundle (Mobile) ──
  {
    id: 'PROD-MOB-ASSOC',
    name: 'Association Bundle',
    serviceType: 'Mobile',
    category: 'Mobile',
    description: 'Offers groups discounted data, voice, and SMS packages, plus essential business services on one platform.',
    fullDescription: 'The Association Bundle offers groups discounted data, voice, and SMS packages, plus essential business services on one platform. Tailored for trade unions, cooperatives, and professional bodies.',
    pricingModel: 'Fixed Pricing (Different packages)',
    productOwner: 'Afua',
    targetSegments: ['SME', 'Large Enterprise', 'Public Sector'],
    technicalRequirements: ['Corporate / Association Master Account', 'Bulk Member MSISDN list'],
    status: 'Active',
    iconName: 'Share2',
    keyFeatures: ['Group voice and data pooling', 'Unified billing to association', 'Self-service admin portal'],
    slaOptions: ['Standard Mobile SLA (99.0%)'],
  },
  // ── 4. Audio Conferencing (Converged) ──
  {
    id: 'PROD-CONV-AUDCONF',
    name: 'Audio Conferencing',
    serviceType: 'Converged',
    category: 'Converged',
    description: 'Enables multiple participants in different locations to join a teleconference by dialling into a central conference bridge.',
    fullDescription: 'Audio Conferencing enables two or more people in different locations to join a teleconference by dialling into a central conference bridge. Participants are charged a minimal fee based on the duration of access to the conference bridge.',
    pricingModel: 'Fixed Pricing (Different packages based on bridge duration and participants)',
    productOwner: 'Afua',
    targetSegments: ['Large Enterprise', 'Multinational', 'Public Sector'],
    technicalRequirements: ['PSTN / Mobile voice access', 'Dedicated Bridge PIN & Access Number'],
    status: 'Active',
    iconName: 'Headphones',
    keyFeatures: ['HD voice quality conference bridge', 'Toll-free and local dial-in numbers', 'Host moderation controls'],
    slaOptions: ['Gold (99.5%)'],
  },
  // ── 5. Auto-Recharge (Mobile) ──
  {
    id: 'PROD-MOB-AUTORECH',
    name: 'Auto-Recharge',
    serviceType: 'Mobile',
    category: 'Mobile',
    description: 'A service offering to organisations and customers to buy airtime in bulk with automated multi-number distribution.',
    fullDescription: 'A service offering to organisation and customers to buy airtime in bulk. It also allows bulk purchase unto multiple numbers automatically on scheduled cycles.',
    pricingModel: 'Fixed Pricing / Bulk Airtime Discount Tiers',
    productOwner: 'Afua',
    targetSegments: ['Large Enterprise', 'SME', 'Public Sector'],
    technicalRequirements: ['Corporate Master Account', 'API or Portal Access for scheduled disbursement'],
    status: 'Active',
    iconName: 'Zap',
    keyFeatures: ['Scheduled automated bulk recharge', 'Real-time disbursement reports', 'Multi-number CSV batch uploads'],
    slaOptions: ['Standard (99.0%)'],
  },
  // ── 6. Bulk SMS (Digital) ──
  {
    id: 'PROD-DIG-BULKSMS',
    name: 'Bulk SMS',
    serviceType: 'Digital',
    category: 'Digital',
    description: 'Allows enterprise clients to send out large volumes of SMS messages instantaneously to target audiences.',
    fullDescription: 'Bulk SMS allows you to send out large amounts of SMS messages at a time. Ideal for promotional campaigns, transaction alerts, and corporate notifications.',
    pricingModel: 'Volume of SMS (Tiered Pricing), Bulk SMS via Ngage may include Platform access fee',
    productOwner: 'Afua',
    targetSegments: ['Large Enterprise', 'SME', 'Public Sector', 'Multinational'],
    technicalRequirements: ['HTTP REST API / SMPP Protocol / Web Portal', 'Sender ID registration with NCA'],
    status: 'Active',
    iconName: 'MessageSquare',
    keyFeatures: ['High throughput (>10,000 SMS/min)', 'Custom Alpha-Numeric Sender ID', 'Detailed delivery receipts (DLR)', 'Ngage campaign management portal'],
    slaOptions: ['Platinum (99.9%)', 'Gold (99.5%)'],
  },
  // ── 7. Business Manager (Digital) ──
  {
    id: 'PROD-DIG-BIZMGR',
    name: 'Business Manager',
    serviceType: 'Digital',
    category: 'Digital',
    description: 'Cloud solution that helps SMEs manage retail operations, accept MoMo payments, and access dashboards and reports.',
    fullDescription: 'Business Manager is a cloud-based solution that helps SMEs manage retail operations, accept MoMo payments, and access dashboards and reports. It is available through the Business Manager web portal and as an Android mobile application.',
    pricingModel: 'Fixed Pricing (Different packages)',
    productOwner: 'Afua',
    targetSegments: ['SME', 'Large Enterprise'],
    technicalRequirements: ['Android Smartphone / Tablet or Web Browser', 'MTN MoMo Merchant Account'],
    status: 'Active',
    iconName: 'Store',
    keyFeatures: ['Integrated MoMo QR payment acceptance', 'Real-time sales & inventory tracking', 'Android mobile app & web portal', 'Automated financial reports'],
    slaOptions: ['Gold (99.5%)'],
  },
  // ── 8. Business Messenger (Digital) ──
  {
    id: 'PROD-DIG-BIZMSG',
    name: 'Business Messenger',
    serviceType: 'Digital',
    category: 'Digital',
    description: 'Prepaid solution providing enterprise clients an application to connect to their audience via SMS, E-mail and Social Media.',
    fullDescription: 'The Business Messenger is a prepaid solution that provides enterprise clients an application to connect to their audience either through SMS, E-mail and Social Media with multi-channel analytics.',
    pricingModel: 'Fixed Pricing (Different packages)',
    productOwner: 'Afua',
    targetSegments: ['Large Enterprise', 'SME'],
    technicalRequirements: ['Web Browser / SaaS Portal', 'Verified Corporate Sender ID'],
    status: 'Active',
    iconName: 'Megaphone',
    keyFeatures: ['Omnichannel SMS, Email, and Social integration', 'Interactive chatbot capabilities', 'Campaign conversion analytics'],
    slaOptions: ['Gold (99.5%)'],
  },
  // ── 9. Chenosis (Digital) ──
  {
    id: 'PROD-DIG-CHENOSIS',
    name: 'Chenosis',
    serviceType: 'Digital',
    category: 'Digital',
    description: 'Pan African Developer Accelerator Platform (DxP) providing APIs, Low-Code/No-Code solutions to build apps faster and cheaper.',
    fullDescription: 'Chenosis is a Pan African Developer Accelerator Platform (DxP) to help developers build applications better, faster and cheaper by providing them with tools such as APIs, Low-Code/No-Code platform solutions across fintech, messaging, and identity verification.',
    pricingModel: 'Type of API (Different prices for different APIs) & Volume of API calls (Tiered Pricing)',
    productOwner: 'Afua',
    targetSegments: ['Large Enterprise', 'SME', 'Multinational'],
    technicalRequirements: ['Developer Portal Access', 'API Key & OAuth 2.0 Credentials'],
    status: 'Active',
    iconName: 'Code',
    keyFeatures: ['Pan-African API marketplace', 'Identity, MoMo, Messaging & Location APIs', 'Low-Code/No-Code workflow builder', 'Developer sandbox environment'],
    slaOptions: ['Platinum (99.95%)', 'Gold (99.9%)'],
  },
  // ── 10. Cloud (Converged) ──
  {
    id: 'PROD-CONV-CLOUD',
    name: 'Cloud',
    serviceType: 'Converged',
    category: 'Converged',
    description: 'Cloud solutions such as compute, storage via local cloud and public cloud such as Microsoft Azure.',
    fullDescription: 'Cloud Solutions such as Compute, storage via local cloud and public cloud such as MS Azure. Tailored for enterprise digital transformation with local data sovereignty and low latency.',
    pricingModel: 'Resource consumption (vCPU, RAM, Storage) / Monthly Subscription',
    productOwner: 'Afua',
    targetSegments: ['Large Enterprise', 'Multinational', 'Public Sector'],
    technicalRequirements: ['Direct Internet Access / MPLS ExpressRoute', 'Hyper-V / VMware / Azure tenant'],
    status: 'Active',
    iconName: 'Cloud',
    keyFeatures: ['Local Ghanaian Data Centre hosting', 'Microsoft Azure ExpressRoute integration', 'Scalable IaaS compute & block storage', 'Disaster recovery and backup replication'],
    slaOptions: ['Platinum (99.95%)', 'Gold (99.9%)'],
  },
  // ── 11. Corporate Postpaid (Mobile) ──
  {
    id: 'PROD-MOB-CORPPOST',
    name: 'Corporate Postpaid',
    serviceType: 'Mobile',
    category: 'Mobile',
    description: 'Reliable, cost-effective, and scalable mobile voice, data, SMS, and CUG services for SMEs and large enterprises.',
    fullDescription: 'MTN Corporate Postpaid provides reliable, cost-effective, and scalable mobile services for SMEs and large enterprises. It offers organizations greater control, flexibility, and cost savings to keep their teams connected and productive.',
    pricingModel: 'Number of SIMs, Package (Data, Voice, SMS, CUG), Customer segment (LE, SME)',
    productOwner: 'Afua',
    targetSegments: ['Large Enterprise', 'SME', 'Public Sector', 'Multinational'],
    technicalRequirements: ['Corporate Master Postpaid Agreement', 'Company Registration & TIN'],
    status: 'Active',
    iconName: 'Smartphone',
    keyFeatures: ['Free on-net CUG calling', 'Itemized corporate billing per cost centre', 'Flexible pooled data bundles', 'Credit limit management'],
    slaOptions: ['Standard Mobile SLA (99.0%)'],
  },
  // ── 12. Data Center Colocation (Converged) ──
  {
    id: 'PROD-CONV-COLO',
    name: 'Data Center Colocation',
    serviceType: 'Converged',
    category: 'Converged',
    description: 'Low-cost rack space and managed IT infrastructure in MTN Tier III Data Centre for tech companies handling large data volumes.',
    fullDescription: 'MTN Co-location solution targets Tech Companies and Companies handling large volumes of data and possibly require secure server connectivity. Offering low-cost rack space, MTN Data Centre manages IT infrastructure, allowing businesses to focus on their operations.',
    pricingModel: 'Rack size, Bandwidth, Redundancy Requirements, Power may be charged in the near future',
    productOwner: 'Afua',
    targetSegments: ['Large Enterprise', 'Multinational', 'Public Sector'],
    technicalRequirements: ['Standard 19-inch rackmount hardware', 'Dual power feed PDUs', 'Cross-connect cabling'],
    status: 'Active',
    iconName: 'Server',
    keyFeatures: ['Tier III certified data center facility', 'Dual redundant power (UPS + Gen-sets)', 'Precision climate control & fire suppression', '24/7 biometric physical security'],
    slaOptions: ['Platinum (99.98%)'],
  },
  // ── 13. Devices (Mobile) ──
  {
    id: 'PROD-MOB-DEVICES',
    name: 'Devices',
    serviceType: 'Mobile',
    category: 'Mobile',
    description: 'Corporate acquisition of mobile devices on a 6, 9, or 12 months amortization schedule with corresponding upfront payments.',
    fullDescription: 'A service that provide a mean for mobile devices to be acquired by Organizations for use with mobile plans - payment terms are on a 12, 9, or 6 months amortization schedule with corresponding upfront payment.',
    pricingModel: 'Number of Devices, Type of Device, Payment Term (One off, amortized), Promo',
    productOwner: 'Afua',
    targetSegments: ['Large Enterprise', 'SME', 'Public Sector'],
    technicalRequirements: ['Corporate credit assessment approval', 'Direct debit / standing order agreement'],
    status: 'Active',
    iconName: 'TabletSmartphone',
    keyFeatures: ['Enterprise smartphone & tablet fleet provisioning', 'Flexible 6/9/12 month financing', 'Warranty and device replacement support'],
    slaOptions: ['Manufacturer Warranty'],
  },
  // ── 14. Dedicated Internet (Fixed) ──
  {
    id: 'PROD-FIXED-DIA',
    name: 'Dedicated Internet',
    serviceType: 'Fixed',
    category: 'Fixed',
    description: 'Dedicated uncontended bandwidth delivered to customer premises via direct connection with fiber, radio or satellite.',
    fullDescription: 'Internet Service with dedicated bandwidth delivered to customer premises via direct connection with fiber, radio or satellite. Solution is postpaid with an MRC payable by customer.',
    pricingModel: 'Medium (Direct Fiber, GPON Fiber, MW, Satellite), Bandwidth, Location (Installation), Redundancy Requirements, Customer Type (Corporate, ISP, NGP), Number of Sites, Contract Term',
    productOwner: 'Eunice',
    targetSegments: ['Large Enterprise', 'Multinational', 'Public Sector'],
    technicalRequirements: ['Direct Fiber / GPON / MW Link', 'Managed CPE Router', 'Static Public IP block'],
    status: 'Active',
    iconName: 'Globe',
    keyFeatures: ['1:1 uncontended symmetrical bandwidth', 'Guaranteed carrier-grade SLA', '24/7 proactive NOC monitoring', 'Static IP addresses included'],
    slaOptions: ['Platinum (99.95%)', 'Gold (99.5%)'],
  },
  // ── 15. Fiber Broadband for Business (Fixed) ──
  {
    id: 'PROD-FIXED-FIBERBIZ',
    name: 'Fiber Broadband for Business',
    serviceType: 'Fixed',
    category: 'Fixed',
    description: 'High-speed shared bandwidth delivered to customer premises via direct fiber connection with prepaid and postpaid options.',
    fullDescription: 'Internet Service with shared bandwidth delivered to customer premises via direct connection with fiber. Solution is both prepaid and postpaid.',
    pricingModel: 'Fixed Pricing (Different packages)',
    productOwner: 'Eunice',
    targetSegments: ['SME', 'Large Enterprise'],
    technicalRequirements: ['MTN Fiber coverage area', 'Optical Network Terminal (ONT) & Wi-Fi Router'],
    status: 'Active',
    iconName: 'Zap',
    keyFeatures: ['Ultra-fast fiber connectivity up to 100Mbps', 'Prepaid & postpaid flexibility', 'Unlimited & capped data bundle tiers'],
    slaOptions: ['Gold (99.0%)'],
  },
  // ── 16. Fixed Voice (Converged) ──
  {
    id: 'PROD-CONV-FIXVOICE',
    name: 'Fixed Voice',
    serviceType: 'Converged',
    category: 'Converged',
    description: 'Enterprise VOIP voice solution provided as an add-on to fixed broadband connectivity services.',
    fullDescription: 'A VOIP solution provided as an addon to broadband services, providing landline numbers with crystal-clear voice clarity.',
    pricingModel: 'Fixed Pricing (Monthly line charge + call tariffs)',
    productOwner: 'Eunice',
    targetSegments: ['Large Enterprise', 'SME'],
    technicalRequirements: ['Broadband connection', 'IP Phone or Voice Gateway (ATA)'],
    status: 'Active',
    iconName: 'PhoneCall',
    keyFeatures: ['Fixed landline number (030xxxxxxx)', 'Discounted enterprise call rates', 'Add-on to existing broadband link'],
    slaOptions: ['Gold (99.5%)'],
  },
  // ── 17. Global MPLS (Fixed) ──
  {
    id: 'PROD-FIXED-GLBMPLS',
    name: 'Global MPLS',
    serviceType: 'Fixed',
    category: 'Fixed',
    description: 'Wide Area Connectivity Service with dedicated bandwidth interconnecting headquarters and international branch offices outside Ghana.',
    fullDescription: 'Wide Area Connectivity Service with dedicated bandwidth delivered to customer premises (Head Office & Branch) via direct connection with fiber, radio or satellite. This interconnects all of customers locations for resource sharing and involves international transit for customers with head office or branch(es) outside of Ghana. Solution is postpaid with an MRC payable by customer.',
    pricingModel: 'Medium (Direct Fiber, GPON Fiber, MW, Satellite), Bandwidth, Number of branches, Location of head office and branches (Installation, International Transit), Redundancy Requirements, Contract Term',
    productOwner: 'Eunice',
    targetSegments: ['Multinational', 'Large Enterprise'],
    technicalRequirements: ['Direct Fiber / Subsea Cable transit', 'Managed MPLS Edge Routers', 'BGP Routing Configuration'],
    status: 'Active',
    iconName: 'Network',
    keyFeatures: ['Global reach via MTN GlobalConnect', 'End-to-end QoS prioritization', 'Symmetrical dedicated international transit', 'Single SLA and support desk across countries'],
    slaOptions: ['Platinum (99.95%)', 'Gold (99.5%)'],
  },
  // ── 18. Hosted PBX (Converged) ──
  {
    id: 'PROD-CONV-HPBX',
    name: 'Hosted PBX',
    serviceType: 'Converged',
    category: 'Converged',
    description: 'Cloud VOIP solution delivering voice, conferencing, and collaboration capabilities via an MTN Hosted platform.',
    fullDescription: 'A VOIP solution that delivers voice, conferencing and other communication and collaboration capabilities to customers via an MTN Hosted platform without on-premise PBX hardware.',
    pricingModel: 'Number of DIDs, Concurrent calls, Extensions, Number of voice calls',
    productOwner: 'Eunice',
    targetSegments: ['Large Enterprise', 'SME', 'Public Sector'],
    technicalRequirements: ['Broadband / DIA connectivity', 'SIP IP Phones / Softphones on PC & Mobile'],
    status: 'Active',
    iconName: 'PhoneForwarded',
    keyFeatures: ['Cloud switchboard with auto-attendant', 'Extension dialing across branches', 'Call recording & voicemail to email', 'Zero hardware maintenance'],
    slaOptions: ['Platinum (99.9%)', 'Gold (99.5%)'],
  },
  // ── 19. Groupshare (Mobile) ──
  {
    id: 'PROD-MOB-GROUPSHARE',
    name: 'Groupshare',
    serviceType: 'Mobile',
    category: 'Mobile',
    description: 'Bulk mobile data solution that allows businesses and unions to disburse data to employees and union members.',
    fullDescription: 'A bulk mobile data solution that allows businesses and unions to disburse to employees and union members seamlessly from a central corporate wallet.',
    pricingModel: 'Fixed Pricing (Volume data bundle tiers)',
    productOwner: 'Eunice',
    targetSegments: ['Large Enterprise', 'SME', 'Public Sector'],
    technicalRequirements: ['MTN Corporate Account', 'Employee / Member MSISDN database'],
    status: 'Active',
    iconName: 'Share2',
    keyFeatures: ['Centralized data allocation management', 'Scheduled or on-demand distribution', 'Real-time usage tracking per member'],
    slaOptions: ['Standard Mobile SLA (99.0%)'],
  },
  // ── 20. IVR (Converged) ──
  {
    id: 'PROD-CONV-IVR',
    name: 'IVR',
    serviceType: 'Converged',
    category: 'Converged',
    description: 'Hosted Interactive Voice Response solution that builds and routes automated call trees for businesses.',
    fullDescription: 'A hosted solution that builds and routes IVR trees for businesses, enabling automated customer self-service, routing to agent queues, and multi-lingual voice prompts.',
    pricingModel: 'Number of recordings & IVR tree branches',
    productOwner: 'Eunice',
    targetSegments: ['Large Enterprise', 'SME', 'Public Sector'],
    technicalRequirements: ['MTN Voice Line / SIP Trunk', 'Custom Audio Prompts / Studio Recordings'],
    status: 'Active',
    iconName: 'PhoneIncoming',
    keyFeatures: ['Multi-level voice menu navigation', 'Time-of-day call routing rules', 'Multi-language audio prompts', 'Integration with CRM & call queues'],
    slaOptions: ['Gold (99.5%)'],
  },
  // ── 21. Leased Lines (Fixed) ──
  {
    id: 'PROD-FIXED-LEASEDLINES',
    name: 'Leased Lines',
    serviceType: 'Fixed',
    category: 'Fixed',
    description: 'Dedicated point-to-point Wide Area Connectivity Service interconnecting head offices and branches for internal resource sharing.',
    fullDescription: 'Wide Area Connectivity Service with dedicated bandwidth delivered to customer premises (Head Office & Branch) via direct connection with fiber, radio or satellite. This interconnects all of customers locations for resource sharing. Solution is postpaid with an MRC payable by customer.',
    pricingModel: 'Medium (Direct Fiber, GPON Fiber, MW, Satellite), Bandwidth, Number of branches, Location of head office and branches (Installation), Redundancy Requirements, Customer Type (Metro, Inter-Regional), Contract Term',
    productOwner: 'Eunice',
    targetSegments: ['Large Enterprise', 'Public Sector', 'Multinational'],
    technicalRequirements: ['Point-to-point Fiber / MW termination', 'Managed Demarcation Device / NTU'],
    status: 'Active',
    iconName: 'Waypoints',
    keyFeatures: ['Dedicated uncontended point-to-point circuit', 'Low latency inter-branch data transport', 'Layer 2 / Layer 3 transparent routing', 'High-availability path protection'],
    slaOptions: ['Platinum (99.95%)', 'Gold (99.5%)'],
  },
  // ── 22. Managed Services (Converged) ──
  {
    id: 'PROD-CONV-MGDSRV',
    name: 'Managed Services',
    serviceType: 'Converged',
    category: 'Converged',
    description: 'Curated bespoke solution to manage networking, IT support and operations for enterprise businesses.',
    fullDescription: 'A solution that curates bespoke requirements to manage the Networking/IT support and operations for businesses. Solution is postpaid with an MRC payable by customer. This can be an addon to an existing service.',
    pricingModel: 'As per customer requirements (Monthly SLA & support scope)',
    productOwner: 'Eunice',
    targetSegments: ['Large Enterprise', 'Multinational', 'Public Sector'],
    technicalRequirements: ['Network audit & asset inventory', 'SLA agreement & escalation matrix'],
    status: 'Active',
    iconName: 'Wrench',
    keyFeatures: ['24/7/365 proactive NOC monitoring', 'On-site & remote IT engineer support', 'Preventive hardware maintenance', 'Monthly operational reporting'],
    slaOptions: ['Platinum (99.95%)', 'Gold (99.9%)'],
  },
  // ── 23. Professional Services (Converged) ──
  {
    id: 'PROD-CONV-PROFSRV',
    name: 'Professional Services',
    serviceType: 'Converged',
    category: 'Converged',
    description: 'Bespoke, one-time project-based solution for customer requirements relating to IT infrastructure and networking.',
    fullDescription: 'A bespoke, one time project-based solution to customer requirements relating to Networking/IT. This can be an addon to an existing service, covering audits, migrations, and architecture design.',
    pricingModel: 'As per customer requirements (Scope of Work / Milestones)',
    productOwner: 'Eunice',
    targetSegments: ['Large Enterprise', 'Multinational', 'Public Sector'],
    technicalRequirements: ['Agreed Statement of Work (SoW)', 'Project charter & milestone plan'],
    status: 'Active',
    iconName: 'Briefcase',
    keyFeatures: ['Network architecture & security auditing', 'Data center migration consulting', 'Turnkey cabling & infrastructure deployment', 'Vendor-certified IT architects'],
    slaOptions: ['Project Milestone SLA'],
  },
  // ── 24. Security (Converged) ──
  {
    id: 'PROD-CONV-SEC',
    name: 'Security',
    serviceType: 'Converged',
    category: 'Converged',
    description: 'Network and application security for enterprise customers including DNS Filtering, Managed Firewall, WAF, and DDoS Protection.',
    fullDescription: 'A solution to provide network and application security to enterprise customers. Solutions include DNS Filtering, Managed Firewall, WAF, etc. in partnership with global cyber leaders such as Cloudflare and Fortinet.',
    pricingModel: 'Type of security solution (Cloudflare, Managed Firewall, etc.), Security Package',
    productOwner: 'Eunice',
    targetSegments: ['Large Enterprise', 'Multinational', 'Public Sector', 'SME'],
    technicalRequirements: ['Edge Firewall Appliance or Cloud Proxy DNS redirection', 'SSL/TLS certificate installation'],
    status: 'Active',
    iconName: 'ShieldCheck',
    keyFeatures: ['Next-Gen Managed Firewall (NGFW)', 'Web Application Firewall (WAF) & DDoS mitigation', 'DNS content filtering & malware blocking', 'Real-time threat intelligence & SOC alerts'],
    slaOptions: ['Platinum (99.95%)', 'Gold (99.9%)'],
  },
  // ── 25. SIP/VOIP (Converged) ──
  {
    id: 'PROD-CONV-SIPVOIP',
    name: 'SIP/VOIP',
    serviceType: 'Converged',
    category: 'Converged',
    description: 'Unified communication and collaboration enablement delivering physical or cloud SIP connection to customer IP-PBX systems.',
    fullDescription: 'A solution that provides unified communication and collaboration enablement by delivering a connection (physical/cloud) to customer\'s communication systems.',
    pricingModel: 'Number of DIDs & Concurrent calls, SIP Connectivity Type (Internet, Leased Line), Medium (Direct Fiber, GPON Fiber, MW, Cloud), Location (Installation), Number of voice calls',
    productOwner: 'Eunice',
    targetSegments: ['Large Enterprise', 'Multinational', 'Public Sector'],
    technicalRequirements: ['Customer IP-PBX / Session Border Controller (SBC)', 'Dedicated Fiber/Data Link or Internet SIP'],
    status: 'Active',
    iconName: 'Radio',
    keyFeatures: ['High-capacity concurrent voice channels (30-1000+ channels)', 'Direct Inward Dialing (DID) blocks', 'Crystal clear HD voice codec support', 'Disaster recovery failover routing'],
    slaOptions: ['Platinum (99.95%)', 'Gold (99.5%)'],
  },
  // ── 26. Sponsored Data (Digital) ──
  {
    id: 'PROD-DIG-SPONSDATA',
    name: 'Sponsored Data',
    serviceType: 'Digital',
    category: 'Digital',
    description: 'Reverse billing solution that allows enterprises to pay for data usage when designated apps or websites are used by their customers.',
    fullDescription: 'A reverse billing solution that allows enterprises to pay for data usage when designated applications or websites are used/visited by their customers, driving digital adoption without customer data cost barriers.',
    pricingModel: 'Volume of Data (Tiered Pricing per GB)',
    productOwner: 'Eunice',
    targetSegments: ['Large Enterprise', 'Public Sector', 'SME'],
    technicalRequirements: ['Customer domain / App URL IP whitelisting', 'MTN Packet Gateway URL routing'],
    status: 'Active',
    iconName: 'Award',
    keyFeatures: ['Zero-rated data access for end users', 'Direct corporate billing per megabyte consumed', 'Real-time traffic analytics dashboard'],
    slaOptions: ['Platinum (99.9%)', 'Gold (99.5%)'],
  },
  // ── 27. Mobile Advertising (Digital) ──
  {
    id: 'PROD-DIG-MOBADV',
    name: 'Mobile Advertising',
    serviceType: 'Digital',
    category: 'Digital',
    description: 'Targeted enterprise mobile messaging and broadcast advertising solutions across subscriber demographics and locations.',
    fullDescription: 'A targeted marketing solution allowing corporate advertisers to reach granular consumer segments based on location, ARPU, device type, and interests via SMS, MMS, and USSD flash messages.',
    pricingModel: 'Volume of SMS (Tiered Pricing)',
    productOwner: 'Eunice',
    targetSegments: ['Large Enterprise', 'SME'],
    technicalRequirements: ['Creative ad copy & target demographic selection', 'Ad regulatory compliance clearance'],
    status: 'Active',
    iconName: 'Megaphone',
    keyFeatures: ['Geo-fenced location targeting', 'Demographic & spend-tier filtering', 'High open rate (>95%)', 'Post-campaign response analytics'],
    slaOptions: ['Campaign Completion SLA'],
  },
  // ── 28. Tertiary Bundle (Mobile) ──
  {
    id: 'PROD-MOB-TERTIARY',
    name: 'Tertiary Bundle',
    serviceType: 'Mobile',
    category: 'Mobile',
    description: 'Subsidized mobile data and voice bundle targeting tertiary institutions like universities and colleges for students and staff.',
    fullDescription: 'A mobile bundle that targets tertiary institutions like universities and colleges, facilitating e-learning, academic research, and campus collaboration with highly subsidized rates.',
    pricingModel: 'Fixed Pricing (Different packages)',
    productOwner: 'Justin',
    targetSegments: ['Public Sector', 'Large Enterprise'],
    technicalRequirements: ['University MOU / Accreditation Agreement', 'Student/Faculty SIM database'],
    status: 'Active',
    iconName: 'GraduationCap',
    keyFeatures: ['Subsidized academic data bundles', 'Whitelisted university portal access', 'Pooled student data allocations'],
    slaOptions: ['Standard Mobile SLA (99.0%)'],
  },
  // ── 29. Toll Free- Mobile (Mobile) ──
  {
    id: 'PROD-MOB-TOLLFREE',
    name: 'Toll Free- Mobile',
    serviceType: 'Mobile',
    category: 'Mobile',
    description: 'Reverse billing solution allowing enterprises to pay for voice calls initiated by their customers to a designated mobile number.',
    fullDescription: 'A reverse billing solution that allows enterprises to pay for calls initiated by their customers to their designated mobile line, removing cost barriers for customer support and sales enquiries.',
    pricingModel: 'Fixed Pricing (Reverse Billing based on inbound call minutes)',
    productOwner: 'Justin',
    targetSegments: ['Large Enterprise', 'Public Sector', 'SME'],
    technicalRequirements: ['Designated MTN Mobile Line / Short Code', 'Reverse billing master profile'],
    status: 'Active',
    iconName: 'PhoneForwarded',
    keyFeatures: ['Free inbound calling for mobile customers', 'Detailed call duration itemized billing', 'Routing to single or multiple contact lines'],
    slaOptions: ['Standard (99.5%)'],
  },
  // ── 30. Toll Free- SIP (Converged) ──
  {
    id: 'PROD-CONV-TOLLFREESIP',
    name: 'Toll Free- SIP',
    serviceType: 'Converged',
    category: 'Converged',
    description: 'Reverse billing solution allowing enterprises to pay for calls initiated by their customers to their designated VOIP line.',
    fullDescription: 'A reverse billing solution that allows enterprises to pay for calls initiated by their customers to their designated VOIP line, routed directly into enterprise call centers and contact platforms.',
    pricingModel: 'Fixed Pricing (Reverse Billing based on incoming minutes + SIP trunk fee)',
    productOwner: 'Justin',
    targetSegments: ['Large Enterprise', 'Public Sector', 'Multinational'],
    technicalRequirements: ['SIP Trunk / IP-PBX Connection', 'Toll-free 0800 / Short Code number allocation'],
    status: 'Active',
    iconName: 'PhoneCall',
    keyFeatures: ['National toll-free number provisioning (0800xxxxxx)', 'Direct SIP termination to contact center', 'Concurrent call capacity scaling'],
    slaOptions: ['Platinum (99.95%)', 'Gold (99.5%)'],
  },
  // ── 31. Turbonet Broadband(WTTX)/FWA (Fixed) ──
  {
    id: 'PROD-FIXED-TURBONET',
    name: 'Turbonet Broadband(WTTX)/FWA',
    serviceType: 'Fixed',
    category: 'Fixed',
    description: 'Wireless broadband solution delivering high-speed internet connectivity via the MTN mobile backbone with prepaid packages.',
    fullDescription: 'A wireless broadband solution that delivers internet connectivity via the MTN mobile backbone. Has prepaid packages businesses can subscribe to with high-gain outdoor/indoor routers.',
    pricingModel: 'Fixed Pricing (Different packages)',
    productOwner: 'Justin',
    targetSegments: ['SME', 'Large Enterprise'],
    technicalRequirements: ['4G / 5G LTE coverage area', 'MTN Turbonet Router with external antenna option'],
    status: 'Active',
    iconName: 'Wifi',
    keyFeatures: ['Plug-and-play instant business broadband', 'High-capacity 4G/5G LTE data bundles', 'Connect up to 32 simultaneous office devices', 'Flexible prepaid top-up options'],
    slaOptions: ['Standard Wireless SLA (99.0%)'],
  },
  // ── 32. USSD (Digital) ──
  {
    id: 'PROD-DIG-USSD',
    name: 'USSD',
    serviceType: 'Digital',
    category: 'Digital',
    description: 'Short code routing solution that allows businesses to run interactive menu applications for their customers on any mobile phone.',
    fullDescription: 'A short code routing solution that allows businesses run user applications for their customers. Works across all mobile phone types without requiring internet connectivity or smartphone capabilities.',
    pricingModel: 'Volume of USSD Hits (Tiered Pricing) + Dedicated Short Code Lease',
    productOwner: 'Justin',
    targetSegments: ['Large Enterprise', 'SME', 'Public Sector'],
    technicalRequirements: ['Short Code (*xxx#) allocation from NCA', 'HTTPS Callback API endpoint'],
    status: 'Active',
    iconName: 'Hash',
    keyFeatures: ['Universal reach across 100% of mobile phones', 'Zero data requirement for end users', 'Fast session initiation (<2 seconds)', 'Integration with MoMo and core banking'],
    slaOptions: ['Platinum (99.95%)', 'Gold (99.9%)'],
  },
  // ── 33. Vehicle Tracking (Converged) ──
  {
    id: 'PROD-CONV-VEHTRACK',
    name: 'Vehicle Tracking',
    serviceType: 'Converged',
    category: 'Converged',
    description: 'IoT telematics solution providing vehicle hardware trackers and data SIMs with internet packages for fleet tracking.',
    fullDescription: 'A solution that provides a vehicle tracker and data SIMs with internet packages for the purpose of tracking, fuel monitoring, geo-fencing, and driver behavior analytics.',
    pricingModel: 'Fixed Pricing (Different packages per vehicle unit)',
    productOwner: 'Justin',
    targetSegments: ['Large Enterprise', 'SME', 'Public Sector'],
    technicalRequirements: ['Vehicle tracker device installation', 'MTN IoT SIM with M2M data package'],
    status: 'Active',
    iconName: 'Truck',
    keyFeatures: ['Real-time GPS fleet location tracking', 'Geo-fencing alerts and speed violation monitoring', 'Fuel level sensing & anti-theft immobilization', 'Mobile app & web dashboard for fleet managers'],
    slaOptions: ['Gold (99.5%)'],
  },
  // ── 34. WebWiz (Digital) ──
  {
    id: 'PROD-DIG-WEBWIZ',
    name: 'WebWiz',
    serviceType: 'Digital',
    category: 'Digital',
    description: 'Prepaid solution allowing businesses to create websites or have websites created for them based on their requirements.',
    fullDescription: 'A prepaid solution that allows businesses to create their websites or have websites created for them based on their requirements, complete with domain name, business emails, and hosting.',
    pricingModel: 'Fixed Pricing (Different packages)',
    productOwner: 'Justin',
    targetSegments: ['SME', 'Large Enterprise'],
    technicalRequirements: ['Domain name registration (.com / .com.gh)', 'Content and branding assets'],
    status: 'Active',
    iconName: 'Monitor',
    keyFeatures: ['Custom website design & rapid deployment', 'Domain registration & corporate email hosting', 'SEO optimization and mobile responsiveness', 'Integrated MoMo payment gateway option'],
    slaOptions: ['Standard Web SLA (99.5%)'],
  },
  // ── 35. Wi-Fi(Public vs Direct) (Fixed) ──
  {
    id: 'PROD-FIXED-WIFI',
    name: 'Wi-Fi(Public vs Direct)',
    serviceType: 'Fixed',
    category: 'Fixed',
    description: 'Dedicated enterprise Wi-Fi or MTN-managed public Wi-Fi over dedicated bandwidth with access points, switches, and captive portal.',
    fullDescription: 'A solution that delivers Wi-Fi over a medium with dedicated bandwidth, Wireless connectivity such as Switches, Access points, wireless controller. Solution can be one-time project based and handed over to customer where customer pays MRC for bandwidth or solution can be MTN managed where billing packages are created.',
    pricingModel: 'Bandwidth, Number of APs, Installation (One time), Support Requirements, Captive Portal Access',
    productOwner: 'Justin',
    targetSegments: ['Large Enterprise', 'Public Sector', 'SME'],
    technicalRequirements: ['Enterprise Wi-Fi Access Points (Cisco/Ruckus)', 'PoE Switch & Managed Gateway', 'Dedicated Internet Bandwidth'],
    status: 'Active',
    iconName: 'Wifi',
    keyFeatures: ['Custom branded captive portal login', 'Enterprise WPA3 security & guest isolation', 'Voucher & SMS OTP authentication', 'Centralized cloud controller management'],
    slaOptions: ['Platinum (99.9%)', 'Gold (99.5%)'],
  },
  // ── 36. Yello Biz/FWA (Converged) ──
  {
    id: 'PROD-CONV-YELLOBIZ',
    name: 'Yello Biz/FWA',
    serviceType: 'Converged',
    category: 'Converged',
    description: 'Integrated solution bundling 4G+ Router, Microsoft 365 subscription, Webwiz website, and Fixed voice service for businesses.',
    fullDescription: 'An integrated solution that bundles wireless connectivity, Microsoft 365 subscription, Webwiz and Fixed voice service for businesses. This is a prepaid solution with subscription packages.',
    pricingModel: 'Fixed Pricing (Different packages)',
    productOwner: 'Justin',
    targetSegments: ['SME', 'Large Enterprise'],
    technicalRequirements: ['4G+ wireless coverage', 'MTN Router + MS 365 tenant setup'],
    status: 'Active',
    iconName: 'Layers',
    keyFeatures: ['All-in-one business starter bundle', 'High-speed wireless broadband router', 'Microsoft 365 Business licenses included', 'Professional company website and landline voice'],
    slaOptions: ['Gold (99.0%)'],
  },
  // ── 37. SD WAN (Converged) ──
  {
    id: 'PROD-CONV-SDWAN',
    name: 'SD WAN',
    serviceType: 'Converged',
    category: 'Converged',
    description: 'Software-Defined Wide Area Network with intelligent multi-path steering and centralized orchestration for enterprise branches.',
    fullDescription: 'Software-Defined Wide Area Network connecting enterprise branch offices, datacenters and multi-cloud environments with dynamic traffic routing, zero-touch provisioning, and integrated security.',
    pricingModel: 'Medium (Direct Fiber, GPON Fiber, MW, Satellite, Mobile), Ownership type (MTN, Customer Owned), Bandwidth, Number of branches (Additional SD WAN router per branch and HQ), Location of head office and branches, Redundancy Requirements, Customer Type (Corporate, ISP, NGP), Contract Term',
    productOwner: 'Justin',
    targetSegments: ['Large Enterprise', 'Multinational', 'Public Sector'],
    technicalRequirements: ['SD-WAN Edge Appliances', 'Underlay WAN links (Fiber/LTE)', 'Central Orchestrator Portal Access'],
    status: 'Active',
    iconName: 'Waypoints',
    keyFeatures: ['Application-aware dynamic path steering', 'Zero-touch remote branch deployment', 'Integrated next-generation security stack', 'Direct cloud SaaS breakout optimization'],
    slaOptions: ['Platinum (99.95%)', 'Gold (99.5%)'],
  },
  // ── 38. Starlink (Converged) ──
  {
    id: 'PROD-CONV-STARLINK',
    name: 'Starlink',
    serviceType: 'Converged',
    category: 'Converged',
    description: 'Satellite solution delivering high-speed low-latency broadband internet connectivity to businesses in remote locations.',
    fullDescription: 'A satellite solution that delivers internet connectivity to businesses. Ideal for mining, agriculture, maritime, and off-grid remote operations across Ghana.',
    pricingModel: 'Device Ownership Option (Outright, Amortized), Data Package, Installation, Contract Term',
    productOwner: 'Justin',
    targetSegments: ['Large Enterprise', 'Public Sector', 'SME'],
    technicalRequirements: ['Clear line-of-sight to open sky', 'Starlink Enterprise Kit (Dish, Mount, Router)', 'Clean AC / Solar Power Supply'],
    status: 'Active',
    iconName: 'Radio',
    keyFeatures: ['High-speed low-earth orbit (LEO) satellite link (up to 220 Mbps)', 'Low latency (25-45ms)', 'Rapid installation anywhere in Ghana', 'Outright or amortized hardware financing'],
    slaOptions: ['Gold (99.0%)'],
  },
  // ── 39. Microsoft 365 (Converged) ──
  {
    id: 'PROD-CONV-M365',
    name: 'Microsoft 365',
    serviceType: 'Converged',
    category: 'Converged',
    description: 'Cloud productivity solution delivering Microsoft licenses (Word, Excel, Outlook, Teams, OneDrive) to businesses.',
    fullDescription: 'A productivity solution that delivers Microsoft licenses to businesses, supported with local billing in Ghana Cedis and dedicated enterprise onboarding support from MTN.',
    pricingModel: 'Fixed Pricing (Different license types: Business Basic, Standard, Premium, E3, E5)',
    productOwner: 'Justin',
    targetSegments: ['Large Enterprise', 'SME', 'Multinational', 'Public Sector'],
    technicalRequirements: ['Internet connection', 'Microsoft Tenant Domain'],
    status: 'Active',
    iconName: 'Laptop',
    keyFeatures: ['Official Microsoft Cloud Solution Provider (CSP) licensing', 'Local GHS billing without foreign exchange risk', 'Exchange Online business email (50GB+)', 'Teams collaboration, SharePoint & 1TB OneDrive cloud storage'],
    slaOptions: ['Microsoft 99.9% Cloud SLA'],
  },
  // ── 40. Operator Connect (Converged) ──
  {
    id: 'PROD-CONV-OPCONNECT',
    name: 'Operator Connect',
    serviceType: 'Converged',
    category: 'Converged',
    description: 'Microsoft solution that allows for Teams calling on the local MTN voice network with direct PSTN dial-in and dial-out.',
    fullDescription: 'A Microsoft solution that allows for teams calling on the local MTN voice network, enabling employees to make and receive external phone calls directly inside Microsoft Teams.',
    pricingModel: 'Number of Users, Package Type (Basic/Plus), Microsoft Teams License, Number of voice calls',
    productOwner: 'Justin',
    targetSegments: ['Large Enterprise', 'Multinational'],
    technicalRequirements: ['Microsoft 365 with Teams Phone licenses', 'MTN Operator Connect Tenant linking'],
    status: 'Active',
    iconName: 'Headphones',
    keyFeatures: ['Seamless PSTN calling inside Microsoft Teams app', 'Zero on-premise hardware / SBC required', 'Managed directly from Microsoft 365 Admin Center', 'Carrier-grade voice routing on MTN Ghana network'],
    slaOptions: ['Platinum (99.95%)', 'Gold (99.5%)'],
  },
  // ── 41. Virtual PBX (Converged) ──
  {
    id: 'PROD-CONV-VPBX',
    name: 'Virtual PBX',
    serviceType: 'Converged',
    category: 'Converged',
    description: 'Cloud-based VOIP solution delivering voice, conferencing and collaboration capabilities via an MTN Hosted platform.',
    fullDescription: 'A VOIP solution that delivers voice, conferencing and other communication and collaboration capabilities to customers via an MTN Hosted platform without on-site hardware investments.',
    pricingModel: 'Number of DIDs, Concurrent calls, Extensions, Number of voice calls',
    productOwner: 'Justin',
    targetSegments: ['Large Enterprise', 'SME'],
    technicalRequirements: ['Broadband connectivity', 'SIP-compliant handsets / Softphones'],
    status: 'Active',
    iconName: 'PhoneCall',
    keyFeatures: ['Multi-branch extension dialling', 'Automated receptionist & call hunt groups', 'Voicemail to email and call forwarding', 'Web management portal for administrators'],
    slaOptions: ['Platinum (99.9%)', 'Gold (99.5%)'],
  },
  // ── 42. Call Center (Converged) ──
  {
    id: 'PROD-CONV-CALLCTR',
    name: 'Call Center',
    serviceType: 'Converged',
    category: 'Converged',
    description: 'Cloud contact center solution delivering voice, conferencing, queue management, agent scoring, and CRM integration.',
    fullDescription: 'A VOIP solution that delivers voice, conferencing and other communication and collaboration capabilities to customers via an MTN Hosted platform with omnichannel routing and supervisor monitoring.',
    pricingModel: 'Number of DIDs, Concurrent calls, Extensions, Number of voice calls',
    productOwner: 'Justin',
    targetSegments: ['Large Enterprise', 'Public Sector', 'Multinational'],
    technicalRequirements: ['Broadband / DIA connectivity', 'Agent USB Headsets & PC Softphones'],
    status: 'Active',
    iconName: 'Headphones',
    keyFeatures: ['Skill-based ACD call queuing', 'Real-time supervisor listen-in & whisper', 'Call recording & quality assurance scoring', 'CRM pop-up and ticketing integration'],
    slaOptions: ['Platinum (99.95%)', 'Gold (99.9%)'],
  },
];
'''

# New slice
new_lines = lines[:start_idx] + [products_seed_code] + lines[end_idx:]
full_text = "".join(new_lines)

# update products initialization to refresh when seed key changes
init_old = """  const [products, setProducts] = useState<EnterpriseProduct[]>(() => {
    const saved = localStorage.getItem(STORAGE_PREFIX + 'products');
    if (saved) return JSON.parse(saved);
    // Seed MTN Ghana products on first load
    if (!localStorage.getItem(PRODUCTS_SEED_KEY)) {
      localStorage.setItem(PRODUCTS_SEED_KEY, 'true');
      localStorage.setItem(STORAGE_PREFIX + 'products', JSON.stringify(MTN_GHANA_PRODUCTS_SEED));
      return MTN_GHANA_PRODUCTS_SEED;
    }
    return [];
  });"""

init_new = """  const [products, setProducts] = useState<EnterpriseProduct[]>(() => {
    if (localStorage.getItem(PRODUCTS_SEED_KEY) !== 'true') {
      localStorage.setItem(PRODUCTS_SEED_KEY, 'true');
      localStorage.setItem(STORAGE_PREFIX + 'products', JSON.stringify(MTN_GHANA_PRODUCTS_SEED));
      return MTN_GHANA_PRODUCTS_SEED;
    }
    const saved = localStorage.getItem(STORAGE_PREFIX + 'products');
    return saved ? JSON.parse(saved) : MTN_GHANA_PRODUCTS_SEED;
  });"""

full_text = full_text.replace(init_old, init_new)

with open('src/context/AppStateContext.tsx', 'w', encoding='utf-8') as f:
    f.write(full_text)

print("Updated AppStateContext.tsx successfully!")
